# filename: .//condor/train_run.sub
universe = vanilla
executable = ./run_vitamin_condor.py_change
getenv  = True
log = .//condor/log/train_run_$(cluster).log
error = .//condor/err/train_run_$(cluster).err
output = .//condor/out/train_run_$(cluster).out
arguments = --gen_train True --start_ind $(start_ind) --num_files 20 --config-file config.ini
accounting_group = ligo.dev.o4.cbc.explore.test
queue
