stages:
  - test
  - build

test:
  stage: test
  image: python
  script:
    - ls
    - pip install ./vitamin
    - python -c "import vitamin"


pages:
  stage: build
  image: python
  script:
  - pip install sphinx sphinx-bootstrap-theme sphinx_rtd_theme nbsphinx 
  - pip install -r requirements.txt
  - python setup.py install
  - sphinx-build -b html . public
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
  - master
